mutation CreateExpense(
  $name: String!
  $totalAmount: Float!
  $payerId: String!
  $debtors: [DebtorInputType!]!
) {
  createExpense(name: $name, totalAmount: $totalAmount, payerId: $payerId, debtors: $debtors) {
    id
    name
  }
}
