query GetDebtSummary {
  getDebtSummary {
    ... on DebtSummary {
      totalAmount
      topDebtors {
        person {
          id
          name
          ... on User {
            email
          }
        }
        amount
      }
    }
    ... on Error {
      errorMessage
    }
  }
}
